services:
  - type: web
    name: laundry-app
    runtime: python
    buildCommand: |
      pip install -r backend/requirements.txt
      cd frontend-react && npm install && npm run build
      mkdir -p ../backend/static
      cp -r dist/* ../backend/static/
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: NEO4J_URI
        sync: false
      - key: NEO4J_USER
        sync: false
      - key: NEO4J_PASSWORD
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30
